<?php
/** @var $block \Wexo\MakeInfluence\Block\Checkout\Success\Tracking */
?>

<?php
    if($block->isS2StrackingEnabled()){
        $data = $block->prepareTrackingData();
        $block->submit($data);
    }
?>

<?php if($block->isFrontendTrackingEnabled()): ?>
<img src="https://makeinfluence.com/p?bid=<?= $block->getBusinessId() ?>&value=<?= $block->getOrderValue() ?>&uid=<?= $block->getOrderId() ?>&promotion_code=<?= $block->getCouponCode() ?>" alt="MakeInfluence Tracking Pixel">
<?php endif; ?>